config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :maps, only: [:index]
  resources :spots do
    resource :wants, only: [:create, :destroy]
  end
  root to: 'users#index'
  get 'maps/index'
  get 'spots/index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :spots
end

app/models/spot.rb
class Spot < ApplicationRecord
  belongs_to :city
  belongs_to :user
  has_many :wants, dependent: :destroy

  has_many :wanted_users, through: :wants, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :spots, dependent: :destroy
  has_many :wants, dependent: :destroy

  has_many :wanted_spots, through: :wants, source: :spot
end

app/models/want.rb
class Want < ApplicationRecord
  belongs_to :user
  belongs_to :spot
  validates :user_id, presence: true, uniqueness: { scope: :spot_id }
  validates :spot_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def index
    @spots = Spot.includes(:city)
    gon.spots = @spots
  end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  def index
    @spots = Spot.includes(:city)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    wanted_spot_ids = current_user.wants.pluck(:spot_id)
    @want_spots = Spot.find(wanted_spot_ids)
  end
end

app/controllers/wants_controller.rb
class WantsController < ApplicationController
  def create
    current_user.wants.create!(spot_id: params[:spot_id])
    redirect_to spots_path
  end

  def destroy
    current_user.wants.find_by(spot_id: params[:spot_id]).destroy!
    redirect_to spots_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Multie</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= include_gon %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= link_to "アカウント編集", edit_user_registration_path %>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, data: { confirm: "ログアウトしますか？" } %>
    <% else %>
      <%= link_to "ログイン", new_user_session_path %>
      <%= link_to "アカウント登録", new_user_registration_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/maps/index.html.erb
<%= javascript_pack_tag 'maps/button', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'maps/makePin', 'data-turbolinks-track': 'reload' %>

  <div class="col-md-9" id="map" style="width:620px; height:400px"></div>

  <script type="text/javascript">
    let map
    let geocoder

    function initMap() {
      geocoder = new google.maps.Geocoder()
      console.log(google.maps.Geocoder())
      var opts = {
        zoom: 12.5,
        center: new google.maps.LatLng(37.9120388, 139.061775)
      };
      map = new google.maps.Map(document.getElementById("map"), opts);
    }
    
  </script>

  <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['API_KEY'] %>&callback=initMap">
  </script>

app/views/spots/_want.html.erb
<% if @wanted_spot_ids.include?(spot.id) %>
  <%= link_to "「行きたい」を取り消す", spot_wants_path(spot), method: :delete %>
<% else %>
  <%= link_to "「行きたい」リストに追加する", spot_wants_path(spot), method: :post %>
<% end %>

app/views/spots/index.html.erb
<h1>観光地一覧</h1>
<% @spots.each do |spot| %>
  <p>市町村名：<%= spot.city.name %></p>
  <p>観光地名：<%= spot.name %></p>
  <p>
    <%= render 'want', spot: spot %>
  </p>
  <hr>
<% end %>

app/views/users/index.html.erb
<h1>OK</h1>
<% @want_spots.each do |spot| %>
  <p><%= spot.name %></p>
<% end %>
<%= link_to "Google Map検索", "https://www.google.com/maps/dir/?api=1&origin=長崎駅&destination=グラバー園", target: :_blank %>

<%# https://www.google.com/maps/dir/?api=1&origin=${keyword}&destination=${keyword} %>